<?xml version="1.0" encoding="UTF-8"?><!--

  Author: Anand patil
  Revision:    1.0
  Date:         04 Mar 2013
  Copyright 2013, All Rights Reserved 
  	
  Copyright (C) Kingfisher Group PLC. All Rights Reserved.
--><definitions targetNamespace="http://www.kingfisher.com/Services/FulfilmentSiteService/1.0" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:koa="http://www.kingfisher.com/oagis/9" xmlns:koaws="http://www.kingfisher.com/Services/FulfilmentSiteService/1.0" xmlns:ns="http://www.openapplications.org/oagis/9" xmlns:ns1="http://www.openapplications.org/oagis/9/IANAMIMEMediaTypes:2003" xmlns:ns2="http://www.openapplications.org/oagis/9/currencycode/54217:2001" xmlns:ns3="http://www.openapplications.org/oagis/9/languagecode/5639:1988" xmlns:ns4="http://www.openapplications.org/oagis/9/unitcode/66411:2001" xmlns:ns5="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1" xmlns:ns6="http://www.openapplications.org/oagis/9/codelists" xmlns:ns7="http://www.openapplications.org/oagis/9/qualifieddatatypes/1.1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <documentation>
    <appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="FulfilmentSiteService_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="SynchroniseFulfilmentSiteJMSBinding" originalBindingStyle="document"/>
        <binding hasEncoding="false" imported="true" name="SynchroniseFulfilmentSiteBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </appinfo>
  </documentation>
	<types>
		<xsd:schema elementFormDefault="qualified" targetNamespace="http://www.kingfisher.com/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:include schemaLocation="FulfilmentSiteService_InlineSchema1.xsd"/>
    </xsd:schema>
	</types>
	<message name="SynchroniseFulfilmentSite">
		<part element="koa:SynchroniseFulfilmentSite" name="Message"/>
	</message>
	<portType name="SynchroniseFulfilmentSitePortType">
		<operation name="SynchroniseFulfilmentSite">
			<input message="koaws:SynchroniseFulfilmentSite"/>
		</operation>
	</portType>
	<binding name="SynchroniseFulfilmentSiteBinding" type="koaws:SynchroniseFulfilmentSitePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="SynchroniseFulfilmentSite">
			<soap:operation soapAction="http://www.kingfisher.com/Services/FulfilmentSiteService/SynchroniseFulfilmentSitePortType/SynchroniseFulfilmentSite/1.0" style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
		</operation>
	</binding>
	<binding name="SynchroniseFulfilmentSiteJMSBinding" type="koaws:SynchroniseFulfilmentSitePortType" xmlns:soapjms="http://www.w3.org/2010/soapjms/">
		<soap:binding style="document" transport="http://www.w3.org/2010/soapjms/"/>
		<soapjms:jndiConnectionFactoryName>kingfisher.jms.ConnectionFactory</soapjms:jndiConnectionFactoryName>
		<soapjms:deliveryMode>PERSISTENT</soapjms:deliveryMode>
		<operation name="SynchroniseFulfilmentSite">
			<soap:operation style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
		</operation>
	</binding>
	<service name="SynchroniseFulfilmentSite">
		<port binding="koaws:SynchroniseFulfilmentSiteBinding" name="SynchroniseFulfilmentSiteBinding">
			<soap:address location="http://www.kingfisher.com/Services/SynchroniseFulfilmentSite/1.0"/>
		</port>
		<port binding="koaws:SynchroniseFulfilmentSiteJMSBinding" name="SynchroniseFulfilmentSiteJMSBinding">
			<soap:address location="jms:jndi:ConfigQueName?targetService=FulfilmentSiteParty&amp;priority=8&amp;userprop=ConfigUserProp"/>
		</port>
	</service>
</definitions>