<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions targetNamespace="https://www.commidea.webservices.com" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:tns="https://www.commidea.webservices.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="commideagateway_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="CommideaGatewaySoap" originalBindingStyle="document"/>
        <binding hasEncoding="false" imported="true" name="CommideaGatewaySoap12" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="https://www.commidea.webservices.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:include schemaLocation="commideagateway_InlineSchema1.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ProcessMsgSoapIn">
    <wsdl:part element="tns:ProcessMsg" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="ProcessMsgSoapOut">
    <wsdl:part element="tns:ProcessMsgResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="CommideaGatewaySoap">
    <wsdl:operation name="ProcessMsg">
      <wsdl:input message="tns:ProcessMsgSoapIn"/>
      <wsdl:output message="tns:ProcessMsgSoapOut"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CommideaGatewaySoap" type="tns:CommideaGatewaySoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ProcessMsg">
      <soap:operation soapAction="https://www.commidea.webservices.com/ProcessMsg" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="CommideaGatewaySoap12" type="tns:CommideaGatewaySoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ProcessMsg">
      <soap12:operation soapAction="https://www.commidea.webservices.com/ProcessMsg" style="document"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CommideaGateway">
    <wsdl:port binding="tns:CommideaGatewaySoap" name="CommideaGatewaySoap">
      <soap:address location="https://txn-qa.cxmlpg.com/XML4LIVE/commideagateway.asmx"/>
    </wsdl:port>
    <wsdl:port binding="tns:CommideaGatewaySoap12" name="CommideaGatewaySoap12">
      <soap12:address location="https://txn-qa.cxmlpg.com/XML4LIVE/commideagateway.asmx"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>