<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSpy v2012 (http://www.altova.com) by A Patil (Kingfisher Information Technology Services UK Ltd) --><!--

  Author: : Anand Patil
  Revision:    1.0
  Date:         22 May 2012
  Copyright 2012, All Rights Reserved 
  	
  Copyright (C) Kingfisher Group PLC. All Rights Reserved.
--><definitions targetNamespace="http://www.kingfisher.com/Services/CommunicationService/1.0" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:koa="http://www.kingfisher.com/oagis/9" xmlns:koaws="http://www.kingfisher.com/Services/CommunicationService/1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <documentation>
    <appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="CommunicationService_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="CommunicationBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </appinfo>
  </documentation>
	<types>
		<xsd:schema elementFormDefault="qualified" targetNamespace="http://www.kingfisher.com/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:include schemaLocation="CommunicationService_InlineSchema1.xsd"/>
    </xsd:schema>
	</types>
	<message name="ProcessCommunication">
		<part element="koa:ProcessCommunication" name="parameter"/>
	</message>
	<message name="AcknowledgeCommunication">
		<part element="koa:AcknowledgeCommunication" name="parameter"/>
	</message>
	<message name="Fault">
		<part element="koa:Fault" name="parameter"/>
	</message>
	<portType name="CommunicationPortType">
		<operation name="ProcessCommunication">
			<input message="koaws:ProcessCommunication"/>
			<output message="koaws:AcknowledgeCommunication"/>
			<fault message="koaws:Fault" name="ProcessCommunicationFault"/>
		</operation>
	</portType>
	<binding name="CommunicationBinding" type="koaws:CommunicationPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="ProcessCommunication">
			<soap:operation soapAction="http://www.kingfisher.com/Services/CommunicationService/CommunicationPortType/ProcessCommunication/1.0"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ProcessCommunicationFault">
				<soap:fault name="ProcessCommunicationFault" use="literal"/>
			</fault>
		</operation>
	</binding>
	<service name="CommunicationService">
		<port binding="koaws:CommunicationBinding" name="CommunicationBinding">
			<soap:address location="http://www.kingfisher.com/Services/CommunicationService/1.0"/>
		</port>
	</service>
</definitions>