<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSpy v2012 (http://www.altova.com) by A Patil (Kingfisher Information Technology Services UK Ltd) --><!--

  Author:  Anand Patil
  Revision:    1.0
  Date:        06 Jan 2012
  Copyright 2012, All Rights Reserved 
  	
  Copyright (C) Kingfisher Group PLC. All Rights Reserved.
--><definitions targetNamespace="http://www.kingfisher.com/Services/ProductAvailabilityService/1.0" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:koa="http://www.kingfisher.com/oagis/9" xmlns:koaws="http://www.kingfisher.com/Services/ProductAvailabilityService/1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <documentation>
    <appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="ProductAvailabilityService_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="ProductAvailabilityBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </appinfo>
  </documentation>
	<types>
		<xsd:schema elementFormDefault="qualified" targetNamespace="http://www.kingfisher.com/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:include schemaLocation="ProductAvailabilityService_InlineSchema1.xsd"/>
    </xsd:schema>
	</types>
	<message name="GetProductAvailability">
		<part element="koa:GetProductAvailability" name="parameter"/>
	</message>
	<message name="ShowProductAvailability">
		<part element="koa:ShowProductAvailability" name="parameter"/>
	</message>
	<message name="Fault">
		<part element="koa:Fault" name="parameter"/>
	</message>
	<portType name="ProductAvailabilityPortType">
		<operation name="GetProductAvailability">
			<input message="koaws:GetProductAvailability"/>
			<output message="koaws:ShowProductAvailability"/>
			<fault message="koaws:Fault" name="GetProductAvailabilityFault"/>
		</operation>
	</portType>
	<binding name="ProductAvailabilityBinding" type="koaws:ProductAvailabilityPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="GetProductAvailability">
			<soap:operation soapAction="http://www.kingfisher.com/Services/ProductAvailabilityService/ProductAvailabilityPortType/GetProductAvailability/1.0"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="GetProductAvailabilityFault">
				<soap:fault name="GetProductAvailabilityFault" use="literal"/>
			</fault>
		</operation>
	</binding>
	<service name="ProductAvailabilityService">
		<port binding="koaws:ProductAvailabilityBinding" name="ProductAvailabilityBinding">
			<soap:address location="http://www.kingfisher.com/Services/ProductAvailability/1.0"/>
		</port>
	</service>
</definitions>