----------------------------------------------------------------------------------------------------------------
--   SQL Create Script	ArticleReference.sql
--   SQL Create Script : Schema MBREPOS.  
--
--   Created By	Vineet More
--   Date	19/06/2013	--
--
--
----------------------------------------------------------------------------------------------------------------
create table MBREPOS.ARTICLEREFERENCE (
LAST_SENT_DATE          VARCHAR2(255),
EANCODE                 VARCHAR2(255),
EANTYPE                 VARCHAR2(255),
SAPTILLTEXT             VARCHAR2(255),
SAPDISCINDICATOR        VARCHAR2(255),
SAPSIZEDESCRIPTION      VARCHAR2(255),
SAPCUSTOMERDESC         VARCHAR2(255),
SAPTAXCLASSIFICATION    VARCHAR2(255),
SAPPRODUCTCLASSCODE     VARCHAR2(255),
SAPBASEUOM              VARCHAR2(255),
SAPMERCHANDISECATEGORY  VARCHAR2(255),
SAPWEIGHTMEASUREIND     VARCHAR2(255),
SAPEMPDISCINDICATOR     VARCHAR2(255),
SAPCOLOUR               VARCHAR2(255),
SAPSIZECODE             VARCHAR2(255),
SAPHAZARDCODE           VARCHAR2(255),
SAPUOM                  VARCHAR2(255),
SAPARTICLEDELETIONFLAG  VARCHAR2(255),
SAPBUSINESSQUALIFIER5   VARCHAR2(255),
SAPPACKSIZE             VARCHAR2(255),
SAPBUSINESSQUALIFIER4   VARCHAR2(255),
SAPBUSINESSQUALIFIER3   VARCHAR2(255),
SAPARTICLEDESC          VARCHAR2(255),
SAPBUSINESSQUALIFIER2   VARCHAR2(255),
SAPBUSINESSQUALIFIER1   VARCHAR2(255),
SAPBUYERCODE            VARCHAR2(255),
SAPCROSSSITESTATUS      VARCHAR2(255),
SAPARTICLETYPE          VARCHAR2(255),
SAPARTICLENUMBER        VARCHAR2(255),
SAPPRICEPROMPT          VARCHAR2(255),
SAPRESTRICTEDSALECODE   VARCHAR2(255))
TABLESPACE "MBODS" NOCOMPRESS LOGGING;